// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh-0Iu1yuwHo015w84tweWtr-Ye2e_jk4',
    appId: '1:732643095648:web:c2eead865872761eb43f05',
    messagingSenderId: '732643095648',
    projectId: 'hearme-app-123',
    authDomain: 'hearme-app-123.firebaseapp.com',
    storageBucket: 'hearme-app-123.firebasestorage.app',
    measurementId: 'G-DVR17XMF8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDut2ZKzQdyWZOAYc_Ia0BIyrkbqUUTVY8',
    appId: '1:732643095648:android:623f9ee61f1cc257b43f05',
    messagingSenderId: '732643095648',
    projectId: 'hearme-app-123',
    storageBucket: 'hearme-app-123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-MRWmmPvP5DsI6a2CB7KVQ8B_V4drYD4',
    appId: '1:732643095648:ios:4e0ae83163e51475b43f05',
    messagingSenderId: '732643095648',
    projectId: 'hearme-app-123',
    storageBucket: 'hearme-app-123.firebasestorage.app',
    iosBundleId: 'com.example.hearmeStudentVoice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-MRWmmPvP5DsI6a2CB7KVQ8B_V4drYD4',
    appId: '1:732643095648:ios:4e0ae83163e51475b43f05',
    messagingSenderId: '732643095648',
    projectId: 'hearme-app-123',
    storageBucket: 'hearme-app-123.firebasestorage.app',
    iosBundleId: 'com.example.hearmeStudentVoice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCh-0Iu1yuwHo015w84tweWtr-Ye2e_jk4',
    appId: '1:732643095648:web:630597c241fc8a59b43f05',
    messagingSenderId: '732643095648',
    projectId: 'hearme-app-123',
    authDomain: 'hearme-app-123.firebaseapp.com',
    storageBucket: 'hearme-app-123.firebasestorage.app',
    measurementId: 'G-E0NTBYBDN6',
  );
}
